toyshop/shopapp/urls.py
from django.urls import path, include

from shopapp.views import index, CategoryShow, CatalogShow, ShowProduct, RegistrationUser, LoginUser, logout_user, FormReviewProduct, \
    aboutList, addMyBasket, MyBasket, dellProductFromBasket

urlpatterns = [
    path('',index, name='home'),
    path('catalog/',CatalogShow.as_view(), name='catalog'),#каталог все товары
    path('category/<slug:slug>',CategoryShow.as_view(), name='category'),#товары в разрезе категории
    path('product/<slug:slug>',ShowProduct.as_view(), name='product'),#продукт
    path('register/',RegistrationUser.as_view(), name='register'),#Регистрация
    path('login/',LoginUser.as_view(), name='login'),#Авторизация
    path('logout/',logout_user,name='logout'),#Выйти из авторизации
    path('review/<slug:slug>', FormReviewProduct.as_view(),name='review'),#Страница отзыв о товаре с формой!
    path('about/',aboutList,name="about"),#страница о нас
    path('mybasket/<int:id>', addMyBasket, name='mybasket'),#добавление товара в корзину
    path('mybasket/', MyBasket.as_view(), name='basket'),#Корзина покупок
    path('dellbasket/<int:id>', dellProductFromBasket, name='dellbasket'),#Удаление из корзины
]

toyshop/toyshop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shopapp.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

toyshop/shopapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.validators import EmailValidator, RegexValidator
from django.core.exceptions import ValidationError

# Create your models here.

#-------------------------------
class Category(models.Model):#Категория товаров
    name = models.CharField(max_length=30, verbose_name='Название категории')
    slug = models.SlugField(max_length=30, verbose_name='URL- категории')
    photo = models.ImageField(upload_to=f'photos/', verbose_name='Фото категории')
    def __str__(self):#Строковое представление модели
        return f'{self.name}'
    def get_absolute_url(self):#ссылка на категорию - как метод
        return reverse('category', kwargs={'slug':self.slug})
    class Meta:# Вложенный класс - для админки
        verbose_name = 'Категория'  # ед
        verbose_name_plural = 'Категории'  # множ
        ordering = ['name']

#------------------------------------------
class Product(models.Model):#Модель товары
    name = models.CharField(max_length=50, verbose_name='Название товара')
    slug = models.SlugField(max_length=50, verbose_name='URL- товара')
    price = models.IntegerField(verbose_name='Цена товара')
    is_sells = models.BooleanField(verbose_name='В продаже')
    photo = models.ImageField(upload_to=f'photos/products/', verbose_name='Фото товара')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, null=True, blank=False, verbose_name='Категория')
    def __str__(self):#Строковое представление модели
        return f'{self.name}'
    def get_absolute_url(self):#ссылка на товар - как метод
        return reverse('product', kwargs={'slug':self.slug})
    class Meta:# Вложенный класс - для админки
        verbose_name = 'Продукт'  # ед
        verbose_name_plural = 'Продукты'  # множ
        ordering = ['name','price','is_sells']

#--------------------------------------------------
class Review(models.Model):#Модель отзыв о товаре - к ней форма!!!!
    reviewText = models.TextField(max_length=1000)
    product = models.ForeignKey(Product,  on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    class Meta:
        verbose_name = 'Отзыв'  # ед
        verbose_name_plural = 'Отзывы'  # множ
        ordering = ['product','user','time_create']

#-----------------------------------------------
class Subscribers(models.Model):#Модель подписчики на скидку - к ней форма!!!!
    name = models.CharField(max_length=30)
    email = models.EmailField()
    tell = models.CharField(max_length=20)

#-----------------------------Модель для корзины покупок-------------------#

class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Покупатель')
    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name='Продукт')
    countProduct = models.SmallIntegerField(verbose_name='Кол-во в заказе',default=1) #Реализовать на странице форму +/-
    priceProduct = models.IntegerField(verbose_name='Цена за шт')
    fullSumm = models.IntegerField(verbose_name='Сумма итого')
    time_create = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    time_update = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    is_buy = models.BooleanField(default=True, verbose_name='Оплачен')
    def __str__(self):#Строковое представление
        return f'Покупатель: {self.user} продукт {self.product}'
    def __iadd__(self, other=1):#Добавление кол-ва товара
        self.countProduct +=other
        return self.countProduct
    def fullSummProduct(self):
        self.fullSumm = self.countProduct * self.priceProduct
        return f'{self.fullSumm}'
    class Meta:
        verbose_name = 'Корзина'  # ед
        verbose_name_plural = 'Корзина'  # множ
        ordering = ['user','is_buy','time_create']

toyshop/shopapp/forms.py
import re

from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import EmailValidator, RegexValidator
from django.core.exceptions import ValidationError
from .models import Subscribers, Review, Basket


class SubscribersForm(forms.ModelForm):
    class Meta:
        model = Subscribers
        fields = ['name','email','tell']
        labels = {
            'name': ('Имя'),
            'email': ('Почта'),
            'tell': ('Телефон'),
        }
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Ваше имя'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Ваш Email'}),
            'tell': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '89995554433'}),
        }


#Форма регистрации пользователя
class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин',widget=forms.TextInput(attrs={'class':'form-input'}))
    password1 = forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class':'form-input'}))
    password2 = forms.CharField(label='Подтверждение пароля',widget=forms.PasswordInput(attrs={'class':'form-input'}))
    email = forms.EmailField(label='Email', widget=forms.EmailInput(attrs={'class':'form-input'}))
    class Meta:
        model = User
        fields = ['username', 'password1', 'password1','email']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-input'}),
            'password1': forms.TextInput(attrs={'class': 'form-input'}),
            'password2': forms.TextInput(attrs={'class': 'form-input'}),
            'email': forms.TextInput(attrs={'class': 'form-input'}),
        }

#Форма авторизации пользователя
class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',widget=forms.TextInput(attrs={'class':'form-input'}))
    password = forms.CharField(label='Пароль',widget=forms.PasswordInput(attrs={'class':'form-input'}))
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-input'}),
            'password': forms.TextInput(attrs={'class': 'form-input'}),
        }


#Форма отзыв о товаре
class FormReview(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewText']
        labels = {
            'reviewText': ('Отзыв о товаре'),
        }
        widgets = {
            'reviewText': forms.Textarea(attrs={'class': 'text_area_rew','placeholder':'Ваш отзыв о товаре'}),
        }

#Форма с кнопкой для добавления товара в корзину
class BasketForm(forms.Form):
    countProduct = forms.CharField(widget=forms.NumberInput())

toyshop/shopapp/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.http import request
from django.shortcuts import render, HttpResponse,reverse, redirect
from django.contrib.auth import authenticate, login,logout
from django.urls import reverse_lazy
from .models import Category, Product, Review, Basket
from django.views.generic import TemplateView, View, ListView, DetailView, CreateView, FormView
from .forms import SubscribersForm, RegisterUserForm, LoginUserForm, FormReview, BasketForm
from datetime import datetime

# Create your views here.


#-------------------
def index(request):#Главная Страница
    if request.method == 'POST':
        form = SubscribersForm(request.POST)
        if form.is_valid():
            try:
                print(form.cleaned_data)
                form.save()
                return redirect('home')
            except:
                form.add_error(None, 'Ошибка отправления данных')
    else:
        title = 'Главная страница сайта'
        form = SubscribersForm()
        category = Category.objects.all()
        productsStaff = Product.objects.filter(category__name='Stuffed Animals', is_sells=True)[:4]
        productsWooden = Product.objects.filter(category__name='Wooden Toys', is_sells=True)[:4]
        contextData = {
        'title':title,
        'category':category,
        'productsStaff':productsStaff,
        'productsWooden':productsWooden,
        'form':form,

        }
        print(request.user.username, request.user.groups, request.user.user_permissions)
        return render(request, 'shopapp/index.html', context=contextData)

#----------------
class CategoryShow(DetailView):#Отобразить товары по категории
    model = Category
    template_name = 'shopapp/category.html'
    slug_url_kwarg = 'slug'
    context_object_name = 'cat'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Группа {self.context_object_name}'
        context['form'] = BasketForm()
        return context
    def form_valid(self,context):
        print(context)
        print(self.request.POST)
        print(self.request.user.username)
        return redirect('catalog')
# def catalog(request):
#     title = 'Каталог сайта'
#     contextData = {
#         'title':title,
#     }
#     return render(request, 'shopapp/catalog.html', context=contextData)
#---------------
class CatalogShow(FormView):#Отобразить каталог товаров
    form_class = BasketForm
    template_name = 'shopapp/catalog.html'
    success_url = reverse_lazy('catalog')
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['cat'] = Category.objects.all()
        context['title'] = f'Каталог товаров'
        return context
    def form_valid(self,form):
        print(self.request.POST)
        return redirect('catalog')


#-----------
class ShowProduct(DetailView):#Просмотр карточки продукта
    model = Product
    template_name = 'shopapp/product.html'
    slug_url_kwarg = 'slug'
    context_object_name = 'product'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'{self.context_object_name}'
        return context

#------------
class FormReviewProduct(FormView):#Форма оставить отзыв о товаре
    form_class = FormReview
    template_name = 'shopapp/review.html'
    slug_url_kwarg = 'slug'
    success_url = reverse_lazy('catalog')
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = Product.objects.get(slug=self.kwargs['slug'])
        name = context['product']
        context['title'] = f'{name}'
        return context
    def form_valid(self, context):#функция передаци данных из формы и внесение в бд данных об отзыве
        review = Review()
        review.reviewText = self.request.POST.get('reviewText')
        review.product = Product.objects.get(slug=self.kwargs['slug'])
        review.user = User.objects.get(id=self.request.user.id)
        review.time_create = datetime.now()
        review.save()
        return redirect('catalog')

#---------------
def aboutList(request):
    title = 'О нас'
    contextData = {
        'title':title,
    }
    return render(request,  'shopapp/about.html', context=contextData)

#---------- Регистрация пользователей - страница с формой на основе базового шаблона плюс свой

class RegistrationUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'shopapp/register.html'
    success_url = reverse_lazy('login')
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Страница регистраиции пользователя'
        return context
    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return reverse_lazy('home')

#Авторизация пользователя
class LoginUser(LoginView):
    form_class = LoginUserForm  # стандартная форма авторизации
    template_name = 'shopapp/login.html'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Страница авторизации пользователя'
        return context
    def get_success_url(self):
        return reverse_lazy('home')

#Выход из авторизации
def logout_user(request):
    logout(request)#Стандартная функция выхода
    return redirect('login')

#Функция добавление в корзину
def addMyBasket(request, id):
    if request.method == "POST":
        basket = Basket()
        product = Product.objects.get(id=id)
        basket.user = User.objects.get(id=request.user.id)
        basket.product = Product.objects.get(id=id)
        basket.priceProduct = product.price
        basket.countProduct = request.POST.get('countProduct')
        basket.fullSumm = int(product.price) * int(request.POST.get('countProduct'))
        basket.save()
    return redirect('home')

#user = User.objects.get(username=request.user)
#basket = user.basket_set.filter(user__id=user.id)

class MyBasket(ListView):#Класс отображение корзины покупок
    model = Basket
    template_name = "shopapp/mybasket.html"
    context_object_name = 'products'
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = User.objects.get(id=self.request.user.id)
        context['fullSum'] = Basket.objects.filter(user__id=self.request.user.id)
        context['title'] = 'Корзина покупок'
        print(context['fullSum'])
        return context

#--------Удаление товара из корзины
def dellProductFromBasket(request,id):
    try:
        product = Basket.objects.get(id=id)
        product.delete()
        return  redirect('basket')
    except:
        return redirect('basket')

toyshop/shopapp/templates/shopapp/about.html
{% extends 'shopapp/base.html' %}

{% block content %}
<main class="main">
	<section class="aboutUs">
		<h2>Интернет-магазин детских игрушек ToyStore</h2>
		<p>Наш магазин занимается реализацией детских игрушек. Весь товар сертифицирован!</p>
		<ul>
			<p>Адрес офиса:</p>
			<li>г. Новосибирск </li>
			<li>ул. Новосибирская 200 оф. 333</li>
			<li>Телефон - <a href="tel:+ 12139745898">+1 213 974-5898</a> </li>
			<li>Электронная почта <a href="mailto:toystore@template.com">toystore@template.com</a></li>
			<p>Адрес Склада:</p>
			<li>г. Новосибирск </li>
			<li>ул. Троллейная 200 склад №333</li>
			<li>Телефон - <a href="tel:+ 12139745898">+1 213 974-5800</a> </li>
			<li>Электронная почта <a href="mailto:toystore@template.com">toystore_sklad@template.com</a></li>
		</ul>
	</section>
</main>
{% endblock content %}

toyshop/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="preconnect" href="https://fonts.googleapis.com">
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500;600&family=Varela+Round&display=swap"
		rel="stylesheet">



	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
	<link type="text/css" href="{% static 'CSS/min_style.css' %}" rel="stylesheet" />
	<link type="text/css" href="{% static 'CSS/style.css' %}" rel="stylesheet" />
	<title>{{title}}</title>
</head>
<body>
	<div class="wrapper">
		{% block header %}
		<div>
			{% for i in basket %}
			<p>{{i}}</p>
			{% endfor %}
		</div>
		<Header class="header">
			<div class="firstHeader">
				<div class="contact_block">
					<div class="tell_email">
						<p class="phone">Call Us: <a href="tel:+ 12139745898">+1 213 974-5898</a></p>
						<p class="email">Email: <a href="mailto:toystore@template.com">toystore@template.com</a></p>
					</div>
					<div class="links_soc">
						<ul class="linksUl">
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/twitter.svg' %}" alt="Твиттер"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/facebook.svg' %}" alt="Фэйсбук"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/insta.svg' %}" alt="Инста"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/drobe.svg' %}" alt="Пинтерест"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/yourtube.svg' %}" alt="Ютуб"></a></li>
						</ul>
					</div>
				</div>
			</div>
			<div class="secondHeader">
				<div class="linksBlock">
					<div class="logo">
						<a href="{% url 'home' %}" class="logoLink">ToyStore</a>
					</div>
					<nav class="links">
						<ul class="navUl">
							<!--Тут реализовать ссылки на страницы -->
							<li class="navLinks"><a href="{% url 'catalog' %}"  target="_blank">Catalog</a></li>
							<li class="navLinks"><a href="#">Delivery</a></li>
							<li class="navLinks"><a href="{% url 'about' %}">About</a></li>
							<li class="navLinks"><a href="#">Contacts</a></li>
						</ul>
					</nav>
					<div class="basket">
						{% if request.user.is_authenticated %}
						<ul class="basketUl">
							<li class="basketLi">Cart</li>
							<li class="basketLi"><a href="{% url 'basket' %}"><img src="{% static 'IMG/links/basket.svg' %}" alt="Корзина"></a></li>
							<li class="basketLi userLi">{{user|capfirst}}</li>
							<li class="basketLi"><a href="{% url 'logout' %}">Выйти</a></li>
						</ul>
						{% else %}
						<ul class="basketUl">
							<li class="basketLi"><a href="{% url 'register' %}">Регистрация</a></li>
							<li class="basketLi"><a href="{% url 'login' %}">Авторизация</a></li>
						</ul>
						{% endif %}
					</div>
				</div>
			</div>
		</Header>	
		{% endblock header %}
		
		{% block content %}
		{% endblock content %}

		{% block footer %}
		<footer class="footer">
			<div class="footerLinks">
				<div class="linksBlock">
					<div class="logo">
						<a href="{% url 'home' %}" class="logoLink">ToyStore</a>
					</div>
					<nav class="liks">
						<ul class="navUl">
							<!--Тут реализовать ссылки на страницы -->
							<li class="navLinks"><a href="{% url 'catalog' %}">Catalog</a></li>
							<li class="navLinks"><a href="#">Delivery</a></li>
							<li class="navLinks"><a href="{% url 'about' %}">About</a></li>
							<li class="navLinks"><a href="#">Contacts</a></li>
						</ul>
					</nav>
					<div class="links_soc">
						<ul class="linksUl">
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/twitter.svg' %}" alt="Твиттер"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/facebook.svg' %}" alt="Фэйсбук"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/insta.svg' %}" alt="Инста"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/drobe.svg' %}" alt="Пинтерест"></a></li>
							<li class="links_item"><a href="#"><img src="{% static 'IMG/links/yourtube.svg' %}" alt="Ютуб"></a></li>
						</ul>
					</div>
				</div>
				
			</div>
			<div class="aboutSite">
				<h3>
					<address>
						Данный сайт (макет сайта) сделан для практики по верстке, js-кодированию и python(Django) - программированию
					</address> 
				</h3>
			</div>
		</footer>	
		{% endblock footer %}

	</div>


	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
	<script src="{% static 'JS/script.js' %}"></script>
</body>
</html>

toyshop/shopapp/templates/shopapp/catalog.html
{% extends 'shopapp/base.html' %}

{% block content %}
<main class="main">
<h2 class="h2Header">Our Catalog</h2>

{% for catGroup in cat %}
<div class="blockWithCat">
	<div class="headerCatalogBlock">
		<div class="headerCatalogBlockImg"><img src="{{catGroup.photo.url}}" alt="{{catGroup.name}}"></div>
		<div class="categoryName">{{catGroup.name}}</div>
	</div>
	<hr>
	<div class="productsCats productsCatsCatalog">
	{% for product in catGroup.product_set.all %}
	{% if product.is_sells %}
	<div class="cartBlock cartBlockCat">
		<img src="{{ product.photo.url }}" alt="{{product.name}}">
		<p><a href="{% url 'product' product.slug  %}">{{product.name}}</a></p>
		<div class="priceBlock">
			{% if request.user.is_authenticated %}
				<form action="{% url 'mybasket' product.id %}" method="POST" class="buyForm" enctype="multipart/form-data">
					{% csrf_token %}
					{{form.countProduct}}
					<input type="submit" value="Купить $ {{product.price}} USD" class="btnSubmit"></input>
				</form>
			{% else %}
			<p>{{product.price}}</p>
			{% endif %}
		</div>
	</div>
	{% endif %}
	{% endfor %}
	</div>
</div>
{% endfor %}

</main>	
{% endblock content %}

toyshop/shopapp/templates/shopapp/category.html
{% extends 'shopapp/base.html' %}
{% block content %}
<main class="main">
<div class="blockWithCat catProducts">
	<div class="headerCatalogBlock">
		<div class="headerCatalogBlockImg"><img src="{{cat.photo.url}}" alt="{{cat.name}}"></div>
		<div class="categoryName">{{cat.name}}</div>
	</div>
	<hr>
	<div class="productsCats productsCatsCatalog">
		{% for product in cat.product_set.all %}
		{% if product.is_sells %}
		<div class="cartBlock cartBlockCat">
			<img src="{{ product.photo.url }}" alt="{{product.name}}">
			<p><a href="{% url 'product' product.slug  %}">{{product.name}}</a></p>
			<div class="priceBlock">
				{% if request.user.is_authenticated %}
				<form  method="POST" class="buyForm" enctype="multipart/form-data">
					{% csrf_token %}
					{{form}}
					<input type="submit" value="Купить $ {{product.price}} USD" class="btnSubmit"></input>
				</form>
				{% else %}
				<p>{{product.price}}</p>
				{% endif %}
			</div>
		</div>
		{% endif %}
		{% endfor %}
	</div>
</div>
</main>
{% endblock content %}

toyshop/shopapp/templates/shopapp/login.html
{% extends 'shopapp/base.html' %}

{% block content %}
<main class="main">
	<h2 class="regH">Авторизация пользователя</h2>
	<form action="{% url 'login' %}" method="post" class="regUserForm">
		{% csrf_token %}
		<p><label class="form-label" for="{{form.username.id_for_label}}">{{form.username.label}}:</label>{{form.username}}</p>
		<div class="form-error">{{form.username.errors}}</div>
		
		<p><label class="form-label" for="{{form.password.id_for_label}}">{{form.password.label}}:</label>{{form.password}}
		</p>
		<div class="form-error">{{form.password1.errors}}</div>
	<div class="divForm">
		<input type="submit" class="regSubmit" value="Авторизация"></input>
	</div>
	</form>
</main>
{% endblock content %}

toyshop/shopapp/templates/shopapp/mybasket.html
{% extends 'shopapp/base.html' %}
{% block content %}
<main class="basketContainer">
	<section class="basketInfo">
		<h1>Корзина покупок пользователя {{user}}</h1>
		<div>
			<table class="table">
				<tr>
					<th>Название товара</th>
					<th>Цена за ед</th>
					<th>Количество</th>
					<th>Сумма</th>
				</tr>
			{% for product in user.basket_set.all %}
				<tr>
					<td>{{product.product}}</td>
					<td>{{product.priceProduct}}</td>
					<td>{{product.countProduct}}</td>
					<td>{{product.fullSumm}}</td>
					<td><a href="{% url 'dellbasket' product.id %}">Удалить</a></td>
					<td><a href="#">Купить</a></td>
				</tr>
			{% endfor %}
			</table>
		</div>
	</section>
</main>


{% endblock content %}

toyshop/shopapp/templates/shopapp/product.html
{% extends 'shopapp/base.html' %}
{% block content %}
<main class="main">
	<div class="cartBlockProducts">
		<div class="leftCartBlockProducts">
			<img src="{{ product.photo.url }}" alt="{{product.name}}" alt="">
		</div>
		<div class="rightCartBlockProducts">
			<h2>{{product.category}}</h2>
			<p>{{product.name}}</p>
			<p>${{product.price}} USD</p>
		</div>
		{% if request.user.is_authenticated %}
		<p><a href="{% url 'review' product.slug %}">Оставить отзыв о товаре </a></p>
		{% else %}
		<p>Для того, чтобы оставить отзыв о нашем товаре - <a href="{% url 'login' %}">АВТОРИЗУЙТЕСЬ</a></p>
		{% endif %}
	</div>
	<div class="blockCommentsGoods">
			{% for comments in product.review_set.all %}
			<div class="divComments">
				<p>Комментарий от пользователя: {{ comments.user }} от: {{ comments.time_create }}</p>
				<p>{{ comments.reviewText }}</p>
			</div>
			<hr>
			{% empty %}
			<div class="divComments">
			<p>Комментариев на данный момент нет</з>
			</div>	
			{% endfor %}
		</ul>
	</div>
</main>
{% endblock content %}

toyshop/shopapp/templates/shopapp/review.html
{% extends 'shopapp/base.html' %}
{% block content %}
<main class="main">
	<div class="review">
		<h2>Добавить отзыв о товаре {{title}}</h2>
		<form action="#" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<p><label class="form-label" for="{{form.reviewText.id_for_label}}">{{form.reviewText.label}}:</label></p>
			<div>
				{{form.reviewText}}
			</div>
			<div class="form-error">{{form.reviewText.errors}}</div>
			<button type="submit"  class="rewSub">Оставить отзыв</button>
		</form>
	</div>
</main>
{% endblock content %}